# Conexión a la Base de Datos
spring.datasource.url=jdbc:mysql://localhost:3306/fc_skills?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root

# Configuración de JPA/Hibernate
# Como ya creamos las tablas a mano con SQL, le decimos a Spring que no intente crearlas de nuevo
spring.jpa.hibernate.ddl-auto=none

# Para ver en la consola las consultas SQL que hace Spring (muy útil para aprender y buscar errores)
spring.jpa.show-sql=true

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
