# Conexión a la Base de Datos
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/fc_skills?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root}

# Configuración de JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update

# Para ver en la consola las consultas SQL que hace Spring (muy útil para aprender y buscar errores)
spring.jpa.show-sql=true

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
file.upload-dir=${FILE_UPLOAD_DIR:frontend/assets/videos}
